# libkperf Java trace local filter configuration.

# Number of shared-memory event slots. Default: 1048576 slots use about 512 MB
# The max num is 67108864 (about 32 GB)
slot_count=1048576

# Call-graph context expansion depth; ignored when include_all=true
context_depth=1

# Maximum number of methods add by context expansion
context_max_methods=128

# Instrument all non-excluded methods when set to true
include_all=false

# Example:
# com.example.service.**
# com.example.Foo::bar
# com.example.Foo::bar(Ljava/lang/String;)V

# Additional classes or methods to instrument besides UTraceAttr symSrc
[include]

# Classes or methos exclude form instrumentation with the highest priority
[exclude]
java.**
javax.**
jakarta.**
jdk.**
sun.**
com.sun.**
org.objectweb.asm.**
net.bytebuddy.**
javassist.**
